{'args': {},
 'data': '{"userString": "abXYZ", "userBool": true, "userNumber": "0.83"}',
 'files': {},
 'form': {},
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate',
             'Content-Length': '63',
             'Content-Type': 'application/json',
             'Host': 'httpbin.org',
             'User-Agent': 'myBotAuto: v1.0.0',
             'X-Amzn-Trace-Id': 'Root=1-67b72332-295cc48b34f7a04322494ed9'},
 'json': {'userBool': True, 'userNumber': '0.83', 'userString': 'abXYZ'},
 'origin': '116.68.18.94',
 'url': 'https://httpbin.org/post'}